name: Build and deploy Python API to Azure Web App - EduLift-Email-API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/email_api.py'  # Runs only when this file changes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout only backend files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend/email_api.py
          fetch-depth: 1  # Fetch only latest commit

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Zip only the API file for deployment
        run: zip release.zip backend/email_api.py

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT authentication
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d backend/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'EduLift-Email-API'
          package: release.zip
          slot-name: 'production'  # Correct slot name (lowercase)

      - name: Set Azure startup command
        run: az webapp config set --resource-group EduLiftResourceGroup --name EduLift-Email-API --startup-file "gunicorn -w 4 -b 0.0.0.0:8000 backend.email_api:app"
